### ISSUE TITLE
excuse me , could you tell me why you close all of the issues? when I use the C3D, I get the same result, what's wrong?

### ISSUE THREAD

**Issue by ilovekj** [RI-CH/SlowFastNetworks#10]

**Comment by r1c7** [comment]
You got exact same results? I used r(2+1)d and slowfastnet, the results I got were different. So can you post the results you got? @ilovekj

**Comment by ilovekj** [comment]
no， i just say it also overfit

**Comment by ilovekj** [comment]
should i use pretrain model

**Comment by r1c7** [comment]
Yes, models trained on UCF101 are easily overfitting. You can use pretrain models,such as model trained on kinetics, as most papers did.   
This issue can also be found in C3D https://github.com/facebook/C3D/issues/42 .

**Comment by ilovekj** [comment]
so, maybe if we load pretrain model on slowfastnetwork,  we can get much
better performance

**Comment by r1c7** [comment]
I think so. But the kinetics  dataset is too large to download, I haven't tested.

**Comment by ilovekj** [comment]
it is hard for us training on kinetics, and i am considering load resnet50 pretrain model, maybe i can get better performance
