### ISSUE TITLE
Did anyone also face the problem of overfitting？

### ISSUE THREAD

**Issue by tomatowithpotato** [RI-CH/SlowFastNetworks#23]
I set lr=0.001， other are default
I train it in UCF101
the top1 accuracy of train is around 73%
the top1 accuracy of test is around 40%

Shocking overfitting！！！！

**Comment by zahidzqj** [comment]
UCF-101 has a limited scale, kinetics-400 can be used.

**Comment by tomatowithpotato** [comment]
thanks for your reply

**Comment by zahidzqj** [comment]
Whether there is a  problem in the code, the accuracy in kinetics-400 is very low?

**Comment by tomatowithpotato** [comment]
> Whether there is a problem in the code, the accuracy in kinetics-400 is very low?

Have you trained on the kinetcis dataset?
Can you share your parameter settings, such as the number of epoch？
