### ISSUE TITLE
accuracy on ucf101 dataset is just 40+%

### ISSUE THREAD

**Issue by 95xueqian** [RI-CH/SlowFastNetworks#3]
i have trained the slowfastNetwork on ucf101 dataset，but the accuracy was just 40+% after 80 epochs

**Comment by RI-CH** [comment]
40% accuracy was tested on validation dataset, right?
Duplicate of #1

**Comment by 95xueqian** [comment]
@RI-CH  the accuracy on train dataset is 78%
