### ISSUE TITLE
size in self.fc maybe dismatch

### ISSUE THREAD

**Issue by CrossLee1** [RI-CH/SlowFastNetworks#5]
In line
https://github.com/RI-CH/SlowFastNetworks/blob/master/lib/slowfastnet.py#L89
`self.fc = nn.Linear(self.fast_inplanes+2048, class_num, bias=False)`

here self.fast_inplanes is 8, but i think it should be 256 after the pooing in fast path, is it right?

**Comment by dannyhung1128** [comment]
Hi @CrossLee1, check out this line of code
https://github.com/RI-CH/SlowFastNetworks/blob/master/lib/slowfastnet.py#L157
SlowFast module adjust its `fast_inplanes` each time when it calls `_make_layer_fast`.

If you print out the model, input dimension of fc layer is exactly 2048+256=2304.
<img width="406" alt="Screen Shot 2019-03-20 at 9 52 33 AM" src="https://user-images.githubusercontent.com/8086170/54653516-e7eca780-4af5-11e9-90cc-8632656082da.png">

**Comment by CrossLee1** [comment]
@dannyhung1128 You're right, thanks :)
