### ISSUE TITLE
K40C * 2 batch_size =4 out of memory

### ISSUE THREAD

**Issue by switchhh** [RI-CH/SlowFastNetworks#9]
Hi! thanks for your great works, I use two K40C each has 12GB memory, crop_size=112,  clip_len=32, I only set batch_size=2 can run it, when I set batch_size=4 it tell me out of memory. But  the Memory Usage is just about 1/10, Volatile GPU-Util is nearly 100%, I don't kown why.

**Comment by Maruidear** [comment]
How did you solve the problem?
